In [4]:
import numpy as np

In [8]:
fruits = ["apple","mango","Orange","Dragon fruit"]
arr = np.array(fruits)
type(np.array(fruits))

numpy.ndarray

In [16]:
things = [["mangoes","apple"],["Jeans","shirts"],["carrot","veggies"]]
goodarr = np.array(things)
goodarr.shape
goodarr.reshape(2,3)
goodarr.dtype

dtype('<U7')

In [15]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [24]:
np.arange(1,20,2).reshape(5,2).shape

(5, 2)

In [28]:
np.linspace(20,2,40).reshape(20,2)

array([[20.        , 19.53846154],
       [19.07692308, 18.61538462],
       [18.15384615, 17.69230769],
       [17.23076923, 16.76923077],
       [16.30769231, 15.84615385],
       [15.38461538, 14.92307692],
       [14.46153846, 14.        ],
       [13.53846154, 13.07692308],
       [12.61538462, 12.15384615],
       [11.69230769, 11.23076923],
       [10.76923077, 10.30769231],
       [ 9.84615385,  9.38461538],
       [ 8.92307692,  8.46153846],
       [ 8.        ,  7.53846154],
       [ 7.07692308,  6.61538462],
       [ 6.15384615,  5.69230769],
       [ 5.23076923,  4.76923077],
       [ 4.30769231,  3.84615385],
       [ 3.38461538,  2.92307692],
       [ 2.46153846,  2.        ]])

In [3]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [5]:
np.zeros(10)
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.ones((5,2,8)).   # 2 rows 8 cloumns, in 3d 5 rows

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [8]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [9]:
# identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [2]:
#print(Random number generation (uniform distribution)
np.random.rand(2,3)

array([[0.1820902 , 0.61818051, 0.8891255 ],
       [0.43614282, 0.40984484, 0.51889828]])

In [3]:
#print(Random number generation following (Normal distribution with mean =0 and std=1 )
np.random.randn(2,3)

array([[-2.32862716,  1.54632849, -0.69462121],
       [ 0.20398759,  0.08284944, -0.12760695]])

In [8]:
#print(Random number generation following (Normal distribution with mean =0 and std=1 )
print(np.random.randn(5,3))

[[ 0.86916853 -0.04526848 -0.6820084 ]
 [ 1.41795014  2.38990288  1.26259669]
 [ 1.22556381 -2.4017365   2.30880734]
 [ 1.56175896 -0.23928586  0.35518898]
 [ 0.82795522  1.46075025 -0.06250588]]


In [6]:
np.random.randint(1,100)

86

In [9]:
np.random.randint(1,100,50)

array([71, 55,  9, 88, 79, 45, 91, 20, 91,  6, 10, 34, 77, 16, 38, 92, 69,
        7,  9, 54, 91, 52, 89, 23, 28, 72, 78, 84, 71, 98, 90, 42,  2, 18,
       52, 26, 51,  7, 60, 23, 68, 26, 84, 60, 76, 76,  5, 80, 13, 16])

In [10]:
np.random.randint(1,100,(4,4))

array([[20, 71,  5, 50],
       [62, 16, 70, 41],
       [25, 83, 12, 72],
       [12, 86, 87, 72]])

In [15]:
st = np.arange(0,11)

In [16]:
st[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
st[2:7]

array([2, 3, 4, 5, 6])

In [24]:
st[-10:7:1]

array([1, 2, 3, 4, 5, 6])

In [25]:
st[-1:7:-1]

array([10,  9,  8])

In [28]:
# 2, 100 random 20 numbers
firstarr = np.random.randint(2,100,20).reshape((5,4))

In [44]:
firstarr[0:5]

array([[74, 18, 93, 76],
       [24, 48, 92, 49],
       [79, 19, 18,  6],
       [28, 72, 70, 77],
       [27, 92, 98, 38]])

In [32]:
#work on row and column slicing seperately in 2d
firstarr[0:3,0:3]

array([[74, 18, 93],
       [24, 48, 92],
       [79, 19, 18]])

In [41]:
firstarr[2:4,1:4]

array([[19, 18,  6],
       [72, 70, 77]])

In [43]:
firstarr[1:3,1:3]

array([[48, 92],
       [19, 18]])

In [53]:
firstarr[0:4:2,1:4:1]

array([[18, 93, 76],
       [19, 18,  6]])

In [1]:
import pandas as pd
import numpy as np

In [4]:
datafra = pd.DataFrame(data=np.arange(1,51).reshape(5,10),index = ["Row1","Row2","Row3","Row4","Row5"],columns = ["1","2","3","4","5","6","7","8","9","10"])

In [7]:
type(datafra)

pandas.core.frame.DataFrame

In [9]:
datafra.head()

1   2   3   4   5   6   7   8   9  10
Row1   1   2   3   4   5   6   7   8   9  10
Row2  11  12  13  14  15  16  17  18  19  20
Row3  21  22  23  24  25  26  27  28  29  30

In [10]:
datafra.tail()

1   2   3   4   5   6   7   8   9  10
Row1   1   2   3   4   5   6   7   8   9  10
Row2  11  12  13  14  15  16  17  18  19  20
Row3  21  22  23  24  25  26  27  28  29  30
Row4  31  32  33  34  35  36  37  38  39  40
Row5  41  42  43  44  45  46  47  48  49  50

In [11]:
datafra.head(2)

1   2   3   4   5   6   7   8   9  10
Row1   1   2   3   4   5   6   7   8   9  10
Row2  11  12  13  14  15  16  17  18  19  20

In [12]:
datafra.describe()

1          2          3          4          5          6  \
count   5.000000   5.000000   5.000000   5.000000   5.000000   5.000000   
mean   21.000000  22.000000  23.000000  24.000000  25.000000  26.000000   
std    15.811388  15.811388  15.811388  15.811388  15.811388  15.811388   
min     1.000000   2.000000   3.000000   4.000000   5.000000   6.000000   
25%    11.000000  12.000000  13.000000  14.000000  15.000000  16.000000   
50%    21.000000  22.000000  23.000000  24.000000  25.000000  26.000000   
75%    31.000000  32.000000  33.000000  34.000000  35.000000  36.000000   
max    41.000000  42.000000  43.000000  44.000000  45.000000  46.000000   

               7          8          9         10  
count   5.000000   5.000000   5.000000   5.000000  
mean   27.000000  28.000000  29.000000  30.000000  
std    15.811388  15.811388  15.811388  15.811388  
min     7.000000   8.000000   9.000000  10.000000  
25%    17.000000  18.000000  19.000000  20.000000  
50%    27.000000  28.000000  29.000000  30.000000  
75%    37.000000  38.000000  39.000000  40.000000  
max    47.000000  48.000000  49.000000  50.000000

In [4]:
datafra[["1","2"]]

1   2
Row1   1   2
Row2  11  12
Row3  21  22
Row4  31  32
Row5  41  42

In [5]:
datafra['1']

Row1     1
Row2    11
Row3    21
Row4    31
Row5    41
Name: 1, dtype: int64

In [7]:
type(datafra['1'])

pandas.core.series.Series

In [8]:
type(datafra[["1","2"]])

pandas.core.frame.DataFrame

In [ ]:
#dataframe == series + series

In [ ]:
#series = row index + respective column

In [ ]:
#Data retrive with repsect to row index

In [10]:
datafra.loc[["Row1","Row2"]]

1   2   3   4   5   6   7   8   9  10
Row1   1   2   3   4   5   6   7   8   9  10
Row2  11  12  13  14  15  16  17  18  19  20

In [11]:
type(datafra.loc[["Row1","Row2"]])

pandas.core.frame.DataFrame

In [ ]:
#Rows has particular index number(index number iloc)
#whenever retrive data from row name use loc
#whenever retrive data from column index name [[]]

In [13]:
datafra.iloc[0:3,0:2] #slicing

1   2
Row1   1   2
Row2  11  12
Row3  21  22

In [14]:
datafra.iloc[0:4,0:3]

1   2   3
Row1   1   2   3
Row2  11  12  13
Row3  21  22  23
Row4  31  32  33

In [15]:
datafra.iloc[2:4,1:3]

2   3
Row3  22  23
Row4  32  33

In [16]:
np.nan #not a number

nan

In [3]:
dt = pd.DataFrame(data=[[1,np.nan,2],[1,3,4],[5,4,3]],index = ["Row1","Row2","Row3"],columns = ["col1","col2","col3"])

In [22]:
dt

col1  col2  col3
Row1     1   NaN     2
Row2     1   3.0     4
Row3     5   4.0     3

In [23]:
dt.isnull()

col1   col2   col3
Row1  False   True  False
Row2  False  False  False
Row3  False  False  False

In [24]:
dt.isnull().sum() #check no of null value in columns

col1    0
col2    1
col3    0
dtype: int64

In [25]:
dt.isna().sum() #check no of null value in columns

col1    0
col2    1
col3    0
dtype: int64

In [27]:
datafra.info

<bound method DataFrame.info of        1   2   3   4   5   6   7   8   9  10
Row1   1   2   3   4   5   6   7   8   9  10
Row2  11  12  13  14  15  16  17  18  19  20
Row3  21  22  23  24  25  26  27  28  29  30
Row4  31  32  33  34  35  36  37  38  39  40
Row5  41  42  43  44  45  46  47  48  49  50>

In [28]:
dt.info

<bound method DataFrame.info of       col1  col2  col3
Row1     1   NaN     2
Row2     1   3.0     4
Row3     5   4.0     3>

In [4]:
dt.head()

col1  col2  col3
Row1     1   NaN     2
Row2     1   3.0     4
Row3     5   4.0     3

In [6]:
##Value counts only for series
datafra['1'].value_counts()

1     1
11    1
21    1
31    1
41    1
Name: 1, dtype: int64

In [7]:
datafra['1'].unique()

array([ 1, 11, 21, 31, 41])

In [8]:
datafra['1'].nunique()

5

In [10]:
datafra[datafra['2']>5]

1   2   3   4   5   6   7   8   9  10
Row2  11  12  13  14  15  16  17  18  19  20
Row3  21  22  23  24  25  26  27  28  29  30
Row4  31  32  33  34  35  36  37  38  39  40
Row5  41  42  43  44  45  46  47  48  49  50

In [12]:
datafra.to_csv('test.csv',index=False)

In [15]:
datafra.to_excel('DataSheet.xlsx') #convert into excel

None


In [ ]:
pd.read_excel('DataSheet.xlsx') # to read files

In [ ]:
pd.read_csv('url',sep="/t") #seperate by comma or tab

In [ ]:
# how to read json format file inthis

In [27]:
#create json
data = '{"Employee_name":"Sunny","Email":"Sunnysunny2gmail.com","profile":[{"title":"Lead","role":"developer"}]}'

In [26]:
data

'{"Employee_name":"Sunny","Email":"Sunnysunny2gmail.com","profile":[{"Lead","role":"developer"}]}'

In [29]:
data1 = pd.read_json(data)

In [33]:
pd.read_json(data,orient='records')

Employee_name                 Email                                 profile
0         Sunny  Sunnysunny2gmail.com  {'title': 'Lead', 'role': 'developer'}

In [34]:
pd.read_json(data,orient='index') #column name changes to row name(Transpose)

0
Employee_name                                     Sunny
Email                              Sunnysunny2gmail.com
profile        [{'title': 'Lead', 'role': 'developer'}]

In [35]:
pd.read_json(data,orient='columns')

Employee_name                 Email                                 profile
0         Sunny  Sunnysunny2gmail.com  {'title': 'Lead', 'role': 'developer'}

In [31]:
data1['salary'] = 100
data1

Employee_name                 Email                                 profile  \
0         Sunny  Sunnysunny2gmail.com  {'title': 'Lead', 'role': 'developer'}   

   salary  
0     100

In [32]:
dict(data1['profile'])[0]['title']

'Lead'

In [2]:
data2 = pd.DataFrame([['a','b'],['c','d']],
  index = ['row1','row2'],columns =['col1','col2'])

In [3]:
data2

col1 col2
row1    a    b
row2    c    d

In [5]:
datafra

1   2   3   4   5   6   7   8   9  10
Row1   1   2   3   4   5   6   7   8   9  10
Row2  11  12  13  14  15  16  17  18  19  20
Row3  21  22  23  24  25  26  27  28  29  30
Row4  31  32  33  34  35  36  37  38  39  40
Row5  41  42  43  44  45  46  47  48  49  50

In [6]:
datafra.to_json(orient='records')

'[{"1":1,"2":2,"3":3,"4":4,"5":5,"6":6,"7":7,"8":8,"9":9,"10":10},{"1":11,"2":12,"3":13,"4":14,"5":15,"6":16,"7":17,"8":18,"9":19,"10":20},{"1":21,"2":22,"3":23,"4":24,"5":25,"6":26,"7":27,"8":28,"9":29,"10":30},{"1":31,"2":32,"3":33,"4":34,"5":35,"6":36,"7":37,"8":38,"9":39,"10":40},{"1":41,"2":42,"3":43,"4":44,"5":45,"6":46,"7":47,"8":48,"9":49,"10":50}]'

In [7]:
datafra.to_json(orient='columns')

'{"1":{"Row1":1,"Row2":11,"Row3":21,"Row4":31,"Row5":41},"2":{"Row1":2,"Row2":12,"Row3":22,"Row4":32,"Row5":42},"3":{"Row1":3,"Row2":13,"Row3":23,"Row4":33,"Row5":43},"4":{"Row1":4,"Row2":14,"Row3":24,"Row4":34,"Row5":44},"5":{"Row1":5,"Row2":15,"Row3":25,"Row4":35,"Row5":45},"6":{"Row1":6,"Row2":16,"Row3":26,"Row4":36,"Row5":46},"7":{"Row1":7,"Row2":17,"Row3":27,"Row4":37,"Row5":47},"8":{"Row1":8,"Row2":18,"Row3":28,"Row4":38,"Row5":48},"9":{"Row1":9,"Row2":19,"Row3":29,"Row4":39,"Row5":49},"10":{"Row1":10,"Row2":20,"Row3":30,"Row4":40,"Row5":50}}'

In [ ]:
datafra.to_json(orient='index')

In [8]:
datafra.to_json()

'{"1":{"Row1":1,"Row2":11,"Row3":21,"Row4":31,"Row5":41},"2":{"Row1":2,"Row2":12,"Row3":22,"Row4":32,"Row5":42},"3":{"Row1":3,"Row2":13,"Row3":23,"Row4":33,"Row5":43},"4":{"Row1":4,"Row2":14,"Row3":24,"Row4":34,"Row5":44},"5":{"Row1":5,"Row2":15,"Row3":25,"Row4":35,"Row5":45},"6":{"Row1":6,"Row2":16,"Row3":26,"Row4":36,"Row5":46},"7":{"Row1":7,"Row2":17,"Row3":27,"Row4":37,"Row5":47},"8":{"Row1":8,"Row2":18,"Row3":28,"Row4":38,"Row5":48},"9":{"Row1":9,"Row2":19,"Row3":29,"Row4":39,"Row5":49},"10":{"Row1":10,"Row2":20,"Row3":30,"Row4":40,"Row5":50}}'

In [ ]:
pd.read_csv("url",header=None)